apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Values.name }}-cluster-role
rules:
  - apiGroups: [""]
    resources: ["pods", "services","nodes"]
    verbs: ["get", "list", "watch"]
