{{- if .Values.security.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.name }}-service-account
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.name }}
{{- end }}
