---
- name: Download Consul Exporter Scraper
  get_url:
    url: "https://github.com/Netmera/consul-exporter-scraper/releases/download/{{ prometheus_consul_exporter_version }}/consul-exporter-scraper_{{ prometheus_consul_exporter_version }}_linux_amd64.tar.gz"
    dest: "/tmp/consul-exporter-scraper.tar.gz"
    mode: "0644"

- name: Extract downloaded file
  unarchive:
    src: "/tmp/consul-exporter-scraper.tar.gz"
    dest: "/tmp"
    remote_src: yes

- name: Create systemd service file
  template:
    src: templates/consul-exporter-scraper.service.j2
    dest: /etc/systemd/system/consul-exporter-scraper.service

- name: Create systemd timer file
  template:
    src: templates/consul-exporter-scraper.timer.j2
    dest: /etc/systemd/system/consul-exporter-scraper.timer

- name: Create /etc/consul-exporter-scraper directory
  file:
    path: "/etc/consul-exporter-scraper"
    state: directory
    mode: "0755"

- name: Move consul-exporter-scraper binary to /usr/local/bin
  command: "mv /tmp/consul-exporter-scraper /usr/local/bin/consul-exporter-scraper"
