---
- name: Clean up temporary files
  file:
    path: "/tmp/{{ item }}"
    state: absent
  with_items:
    - consul-exporter-scraper.tar.gz
    - consul-exporter-scraper
    - configs
    - README.md
    - LICENSE