{{ range . }}
{
  "services": [
    {
      "id": '{{.environment}}',
      "name": '{{.hostname}}',
      "address": '{{.address}}',
      "port": {{.port}},
      "meta": {
        "env": '{{.environment}}',
        "type": '{{.exporterType}}'
      }
    }
  ]
}