{
    "consuladress": "", #consul address
    "exporters": [
        {"name": "Mongo Exporter", "port": 27017, "exporttype": "mongodb"},
        {"name": "Kafka Exporter", "port": 9092, "exporttype": "kafka"},
        {"name": "Cassandra Exporter", "port": 9042, "exporttype": "cassandra"},
        {"name": "ClickHouse Exporter", "port": 8123, "exporttype": "clickhouse"},
        {"name": "Node Exporter", "port": 9100, "exporttype": "node-exporter"}
    ]
}
